version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

  pre_build:
    run-as: root
    commands:
      - 'echo Installing project npm packs'
      - 'npm install'

  build:
    commands:
      - echo Build started on $(date +%Y-%m-%d)
      - npm run build

  post_build:
    commands:
      # Clear S3 bucket.
      - aws s3 rm s3://${S3_BUCKET} --recursive
      - echo S3 bucket "${S3_BUCKET}" cleared

      # Copy files
      - aws s3 cp build s3://${S3_BUCKET}/ --recursive
      - aws s3 cp s3://$S3_BUCKET/index.html s3://${S3_BUCKET}/index.html --metadata-directive REPLACE --cache-control max-age=0

      # Clear invalidation
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION} --paths /static/* /index.html

      # Tells us its ok
      - echo Build completed on $(date +%Y-%m-%d)
